create extension if not exists "pgcrypto";
create table if not exists profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text, email text, phone text, company_name text, country text, role text not null default 'customer', avatar_url text, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists product_categories (id uuid primary key default gen_random_uuid(), name text not null, slug text unique not null, description text, image_url text, display_order int default 0, is_active boolean default true, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists products (id uuid primary key default gen_random_uuid(), category_id uuid references product_categories(id), name text not null, slug text unique not null, short_description text, description text, product_code text, cas_number text, molecular_formula text, molecular_weight text, purity text, packaging text, origin text, application text, specifications jsonb default '[]', image_url text, is_featured boolean default false, is_active boolean default true, display_order int default 0, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists product_images (id uuid primary key default gen_random_uuid(), product_id uuid references products(id) on delete cascade, image_url text, storage_path text, alt_text text, display_order int default 0, created_at timestamptz default now());
create table if not exists inquiries (id uuid primary key default gen_random_uuid(), product_id uuid references products(id), user_id uuid references auth.users(id), name text not null, email text not null, phone text, company text, country text, quantity text, message text, status text not null default 'pending' check(status in ('pending','reviewing','quoted','completed','cancelled')), created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists contact_messages (id uuid primary key default gen_random_uuid(), name text not null, email text not null, phone text, company text, subject text, message text not null, status text not null default 'new', created_at timestamptz default now());
create table if not exists quotations (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id), inquiry_id uuid references inquiries(id), quote_number text unique, status text default 'draft', total_amount numeric, currency text default 'USD', notes text, created_at timestamptz default now(), updated_at timestamptz default now());
alter table profiles enable row level security; alter table product_categories enable row level security; alter table products enable row level security; alter table product_images enable row level security; alter table inquiries enable row level security; alter table contact_messages enable row level security; alter table quotations enable row level security;
